### ISSUE TITLE
html email to markdown returns unsatisfactory results

### ISSUE THREAD

**Issue by SL-Gundam** [thephpleague/html-to-markdown#130]
I'm trying to use this library to convert html emails to markdown

I've set strip_tags to true and false. They did not provide a different result

Attached you will find two txt files
[Original html.txt](https://github.com/thephpleague/html-to-markdown/files/856015/Original.html.txt) contains the original html content from the email
[Markdown result.txt](https://github.com/thephpleague/html-to-markdown/files/856016/Markdown.result.txt) This is the result after this library did its work

I still see a number of span tags that i believe should have been stripped when strip_tags is set to true

Any reason why it did not work?

**Comment by colinodell** [comment]
This seems to be a bug with how we handle `<pre>` tags. See:

 - https://github.com/thephpleague/html-to-markdown/blob/master/src/HtmlConverter.php#L152
 - #26

**Comment by taiyeoguns** [comment]
Hi @colinodell,

What's the best way to fix this? Is it sufficient to remove `<pre>` from the array in HtmlConverter L152?

**Comment by andreskrey** [comment]
No, because you would end up converting to markdown the html inside CODE tags.

This is a tricky situation. AFAIK Commonmark doesn't define how lone pre tags should be treated. All the code references [show pre tags next to code tags](http://spec.commonmark.org/0.12/#example-92) so it's kinda hard to define what should be done if this project wants to respect 100% the commonmark definition.
