### ISSUE TITLE
Autoloader not defined

### ISSUE THREAD

**Issue by andreamoro** [thephpleague/html-to-markdown#167]
Appreciate this is not a "real" issue, but having used in the past the v. 2.8.x that was all in one file, I now struggle to update to the most recent version not being able to use composer.

Any chance to add the __autoload method in each files or as in a general routine so to save the hassle to everybody willing to play with the class quickly?

**Comment by colinodell** [comment]
Unfortunately, Composer is the only supported installation method (#95).  We do not have any plans to create a dedicated autoload file for non-Composer installations.

In my personal experience, it should be possible to use Composer to install libraries like this into legacy projects.  You may need to customize things like [where the `vendor` dir is placed](https://getcomposer.org/doc/06-config.md#vendor-dir), or update your code to [use `spl_autoload_register` instead of `__autoload`](http://php.net/spl_autoload_register) to support multiple autoloaders, but it should be doable.  I'd be more than happy to offer any further advice on making that change so you can successfully use Composer with your project - just let me know! :smiley:

**Comment by colinodell** [comment]
Using an autoloader would be the easiest approach.  Otherwise, you could try a workaround like running `require_once` for all files in this library (maybe even automate that with some additional PHP?)
