### ISSUE TITLE
Files and directorys are wrong for autolinking

### ISSUE THREAD

**Issue by strider72** [thephpleague/html-to-markdown#190]
The filename and directory structure should follow the standard structure for PHP to easily autolink Classes. Your namespaces don't match your folder structure.  With this class, I either have to add a "use" statement" or enter the full namespace when creating an object.  No other Composer package I use has this issue.

**Comment by colinodell** [comment]
This library follows the PSR-4 standard and seems to be working. You are correct that your coffee will needed to have "use" statement which reference the namespace so that Composer's autoloader can done them - this is typical for any Composer-installed package.

If you still believe there's an issue, would you mind sharing the exact error message you're seeing, and perhaps the code that's referencing this library?

**Comment by strider72** [comment]
The issue has something to do with the disparity between the namespace and the actual file names, e.g. "HTMLToMarkdown" vs. "html-to-markdown".

When I use (for example) the Parsedown library , I can just call `new \Parsedown()`; but with your library I have to call `new \League\HTMLToMarkdown\HtmlConverter()`

**Comment by strider72** [comment]
Of maybe Parsedown is doing something unusual that makes their classes easier to find? Hmm.

**Comment by strider72** [comment]
Ooooookay. Never mind.  Parsedown doesn't use a namespace. It's a global class, it appears.

Sorry for the confusion.
