### ISSUE TITLE
Support a chain-of-responsibility/visitors on the elements

### ISSUE THREAD

**Issue by tomzx** [thephpleague/html-to-markdown#46]
The current implementation expects only a single converter per HTML tag. However, it makes it hard to do things such as having multiple processing passes on the same tag.

For example, I have the following:

```
<span class="c1 c5">Some text</span>
```

With a chain-of-responsibility/visitors, we could have multiple parsers going through the element and manipulate it. One of the converter could, for instance, see that the span has a class **c5**, and modify the value of the element and make it bold.

```
<span class="c1 c5">**Some text**</span>
```

I've already implemented something like this @ https://github.com/TomzxForks/html-to-markdown/tree/features/chain-of-responsibility. It builds on my other change where I add a preProcess/postProcess step when we're walking through the HTML tree.

**Comment by colinodell** [comment]
I really like the idea.  What do you think about using an event dispatcher instead of overrideable method?  That way multiple things can hook into the pre/post-process events without needing to rely on inheritance or implementing a custom solution - we simply dispatch the event and let the listeners do whatever they need to.  Thoughts?

**Comment by tomzx** [comment]
Event dispatching sounds like a solution.

Are you thinking about a global dispatcher/events or more of a observer/subject kind of event dispatching? In the case of observers/subject, what would be the subject (class on which you can attach observers)?
