### ISSUE TITLE
convert link to Jira markdown

### ISSUE THREAD

**Issue by lwrbakro** [thephpleague/html-to-markdown#56]
Hi,

I am about to convert HTML code to JIRA markdown.

Is it possible to use custom converter function instead the default one?

```
<a href="http://example.com">link title</a>  ==> [link title|http://example.com]
```

**Comment by colinodell** [comment]
You could use a custom converter if you had the ability to configure the `Environment`:

1. Create the custom converter (implement the `ConverterInterface`)
2. Configure your own `Environment`
  * Copy [lines 83-98 of `Environment`](https://github.com/thephpleague/html-to-markdown/blob/master/src/Environment.php#L83-L98)
  * Change [line 93](https://github.com/thephpleague/html-to-markdown/blob/master/src/Environment.php#L93) to add your custom converter instead of the core one

At this point you've got the `Environment` configured how you need it, but no way to inject this into the `HtmlConverter`.  This is an oversight on my part.  For now, you could use (ab)use inheritence:

~~~
class CustomHtmlConverter extends HtmlConverter
{
    public function __construct(Environment $environment, array $options = array()) {
        parent::__construct($options);

        $this->environment = $environment;
        $this->environment->getConfig()->merge($options);
    }
}
~~~

I'll open a separate issue to make the `Environment` injectable.

**Comment by colinodell** [comment]
Oops, I misread my own code (I haven't had my coffee yet this morning). Turns out you **can** do this with the existing code:

1. Create the custom converter (implement the `ConverterInterface`)
2. Initialize a new `HtmlConverter`.
3. Call `$htmlConverter->addConverter(new MyCustomLinkConverter())`

That third call will replace the existing link converter with yours :)
