### ISSUE TITLE
`<code>` with not text-only content shouldn't use backticks

### ISSUE THREAD

**Issue by marijnvdwerf** [thephpleague/html-to-markdown#74]
**Input**:

``` html
<p>Did you check use the <code>PHPUnit_Framework_Test<em>Case</em></code>?</p>
```

**Actual**:

``` md
Did you check use the `PHPUnit_Framework_Test<em>Case</em>`?
```

**Expected**:

``` md
Did you check use the <code>PHPUnit_Framework_Test*Case*</code>?
```

**Comment by andreskrey** [comment]
I think this is not a bug. The supplied text in the example is not correct. Tags inside code tags should be escaped. Otherwise browsers will either ignore or render them, instead of displaying the full tag.

A correct example would be:

**Input**:

    <p>Did you check use the <code>PHPUnit_Framework_Test&lt;em&gt;Case&lt;/em&gt;</code>?</p>

**Actual**:

    Did you check use the `PHPUnit_Framework_Test<em>Case</em>`?

**Expected**:

    Did you check use the `PHPUnit_Framework_Test<em>Case</em>`?

Also I couldn't find any reference on the CommonMark spec (0.26) saying that inner code tags should be rendered as markdown.

Am I missing something?

**Comment by marijnvdwerf** [comment]
I meant it to be 'italic inside code'. So rendering like: <code>PHPUnit_Framework_Test<em>Case</em></code>

**Comment by andreskrey** [comment]
So you mean that the rules should be:

- If there are no non-escaped html tags within the code tag, behave as normal
- If there are non-escaped html tags within the code tags, don't use the backticks, keep the `<code>` tag and render the inner tags?

Also, wouldn't that change be a "breaking backwards compatibility" change? The current behavior of the code tag is to leave the inner tags alone, escaped or not.

**Comment by MrPetovan** [comment]
Per CommonMark, no styling is done between backticks. Conversely, we have to assume any HTML tag inside a `<code>` tag is meant as literal tags with no styling.

See https://spec.commonmark.org/dingus/?text=Did%20you%20check%20use%20the%20`PHPUnit_Framework_Test*Case*`?

**Comment by colinodell** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code, "phrasing content" (including `<em>`) is valid inside of `<code>` tags.

This issue is similar to #62 - in both cases we're doing a naïve conversion without essentially checking whether the result is CommonMark-compatible and produces the same HTML in reverse.  (Of course we don't actually want to actually perform the two-way conversion to check it - we instead want to have other logic to determine whether the conversion should be made the "usual" way or not).

> Per CommonMark, no styling is done between backticks.

Yeah, so in this case we should **not** use backticks but leave the `<code>` as-is.

> Also, wouldn't that change be a "breaking backwards compatibility" change?

Strictly speaking, SemVer only concerns itself with backwards compatibility at the code API level.  Some take this a step further and say that ANY BC-break calls for a new major version, but in the case of converters like this I feel that BC-breaks are entirely acceptable when they improve conversion results without API changes.

So ultimately I would like to get solutions for this and #62, it just hasn't been a priority yet :upside_down_face:
